### PR TITLE
Added video input select 

### PR DESCRIPTION
**Pull request by HiDefDan**
Tested on Panasonic RZ31k with security disabled. 
First timer for pull request - sorry if it's a mess. I am keen to learn

### CODE REVIEW

**Review by JeffreyDavidsz — CHANGES_REQUESTED** [review]
It looks like you've added some actions double now (freeze for example), and missing the actual command in this pull request.

**Comment by HiDefDan** [comment]
> It looks like you've added some actions double now (freeze for example), and missing the actual command in this pull request.

Oops! what a dumb thing to do...

I have edited the file and it should now be as I intended.

**Review by JeffreyDavidsz — CHANGES_REQUESTED** [review]
This will populate the list with commands, but it will do nothing. You will need the actual command also like for example;
`case 'inputSelect':
  cmd = '%1????? ' + action.options.inputNum;
  break;`
In the list down your code

**Comment by HiDefDan** [comment]
> This will populate the list with commands, but it will do nothing. You will need the actual command also like for example;
> `case 'inputSelect': cmd = '%1????? ' + action.options.inputNum; break;`
> In the list down your code

Sorry again. More haste less speed. I need to fully work out how to use git on the command line - keep getting my password refused so I’ve been working via web 🤦‍♂️

**Comment by JeffreyDavidsz** [comment]
Normally I use atom to push my commits into Companion, but always web to create a pull request. If your commit to the fork is good, the pull request will match that

**Comment by HiDefDan** [comment]
Thanks for the tips and your patience. 

I will retest the code on a projector this morning to ensure that I am happy with it. I’ve been sat on it since last November meaning to get around to it - I probably should have spent another 24 hours making sure I was submitting it without stupid copy/paste errors 🙄

**Pull request closed without merging**
